version: '3'
services:
  zookeeper:
    build:
        context: .
        dockerfile: Dockerfile.zookeeper
    networks:
      - ch_sharded
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2182:2181"
      - "2888:2888"
      - "3888:3888"
    
  clickhouse10:
    build:
        context: .
        dockerfile: Dockerfile.clickhouse
    environment:
      - SHARD=01
      - REPLICA=01
    ports:
      - "8011:9000"
      - "9132:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_sharded
    depends_on:
      - zookeeper
      
  clickhouse11:
    build:
        context: .
        dockerfile: Dockerfile.clickhouse
    environment:
      - SHARD=01
      - REPLICA=02
    ports:
      - "8012:9000"
      - "9133:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_sharded
    depends_on:
      - zookeeper
      
  clickhouse12:
    build:
        context: .
        dockerfile: Dockerfile.clickhouse
    environment:
      - SHARD=01
      - REPLICA=03
    ports:
      - "8013:9000"
      - "9134:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_sharded
    depends_on:
      - zookeeper
      
  clickhouse13:
    build:
        context: .
        dockerfile: Dockerfile.clickhouse
    environment:
      - SHARD=02
      - REPLICA=01
    ports:
      - "8014:9000"
      - "9135:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_sharded
    depends_on:
      - zookeeper
      
  clickhouse14:
    build:
        context: .
        dockerfile: Dockerfile.clickhouse
    environment:
      - SHARD=02
      - REPLICA=02
    ports:
      - "8015:9000"
      - "9136:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_sharded
    depends_on:
      - zookeeper
      
  clickhouse15:
    build:
        context: .
        dockerfile: Dockerfile.clickhouse
    environment:
      - SHARD=02
      - REPLICA=03
    ports:
      - "8016:9000"
      - "9137:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_sharded
    depends_on:
      - zookeeper
      
  clickhouse16:
    build:
        context: .
        dockerfile: Dockerfile.clickhouse
    environment:
      - SHARD=03
      - REPLICA=01
    ports:
      - "8017:9000"
      - "9138:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_sharded
    depends_on:
      - zookeeper
      
  clickhouse17:
    build:
        context: .
        dockerfile: Dockerfile.clickhouse
    environment:
      - SHARD=03
      - REPLICA=02
    ports:
      - "8018:9000"
      - "9139:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_sharded
    depends_on:
      - zookeeper
      
  clickhouse18:
    build:
        context: .
        dockerfile: Dockerfile.clickhouse
    environment:
      - SHARD=03
      - REPLICA=03
    ports:
      - "8019:9000"
      - "9140:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_sharded
    depends_on:
      - zookeeper
      
  clickhouse19:
    build:
        context: .
        dockerfile: Dockerfile.clickhouse
    environment:
      - SHARD=04
      - REPLICA=01
    ports:
      - "8020:9000"
      - "9141:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_sharded
    depends_on:
      - zookeeper
      
  clickhouse20:
    build:
        context: .
        dockerfile: Dockerfile.clickhouse
    environment:
      - SHARD=04
      - REPLICA=02
    ports:
      - "8021:9000"
      - "9142:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_sharded
    depends_on:
      - zookeeper
      
  clickhouse21:
    build:
        context: .
        dockerfile: Dockerfile.clickhouse
    environment:
      - SHARD=04
      - REPLICA=03
    ports:
      - "8022:9000"
      - "9143:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_sharded
    depends_on:
      - zookeeper
networks:
  ch_sharded:
    driver: bridge